In [5]:
import numpy as np

In [6]:
#a numpy array does real math on every element
price = np.array([100,200,300,400,500])
print(price*2)

[ 200  400  600  800 1000]


In [7]:
#add 10% VAT in every price list
price = np.array([100,200,300,400,500])
print(price * 1.10)


[110. 220. 330. 440. 550.]


In [8]:
#array also do math element by element with each other
shop_a = np.array([1,2,3])
shop_b = np.array([11,12,13])
print(shop_a+shop_b)

[12 14 16]


In [9]:
#make an array from a list
a = np.array([10,11,14,17,20])
print(a)
print(type(a))

[10 11 14 17 20]
<class 'numpy.ndarray'>


In [10]:
#every array has useful attributes
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size )

(5,)
1
int64
5


In [11]:
#Initializing array
    #a)
#zeros_all zero
print(np.zeros((2,3)))


[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#b)one-all one
print(np.ones((4,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
#c)full
print(np.full((3,5),7))

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [14]:
#d)eye
print(np.eye(7))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [15]:
#range:arang and linspace
print(np.arange(0,10,2))
print(np.arange(8))
print(np.linspace(0,7,11))

[0 2 4 6 8]
[0 1 2 3 4 5 6 7]
[0.  0.7 1.4 2.1 2.8 3.5 4.2 4.9 5.6 6.3 7. ]


In [16]:
#random arrays
print(np.random.rand(3))
print(np.random.rand(2,2))
print(np.random.randint(1,100,5))

[0.05825988 0.54787631 0.62897456]
[[0.07840133 0.62364326]
 [0.02677902 0.8306997 ]]
[87 54 15 71 47]


In [17]:
#indexing and slicing 1D array
arr = np.array([10,20,30,40,50])
print(arr[2])
print(arr[3])
print(arr[1:4])
print(arr[::2])

30
40
[20 30 40]
[10 30 50]


In [18]:
#indexing and slicing(2D array)
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m[0,0])
print([1,2])

1
[1, 2]


In [20]:
#use : to take whole row or colom
print(m[0])
print(m[:,0])
print(m[0:2,1:3])

[1 2 3]
[1 4 7]
[[2 3]
 [5 6]]


In [22]:
#max,mim,argmax,argmin
v = np.array([12,34,56,7])
print(v.max())
print(v.min())
print(v.argmax())
print(v.argmin())

56
7
2
3


In [ ]:
#1. Make a 1D array of these 6 product prices `[500, 1200, 250, 3200, 780, 60]` and add **15% VAT** to all of them at once.
#2. Create a 3×3 array of all zeros. Then create a 3×3 array where every value is 9.
#3. Use `arange` to make `[0, 5, 10, ... , 50]`. Then use `linspace` to make 5 evenly spaced numbers from 0 to 100.
#4. Given `marks = [72, 88, 65, 91, 80]` and `names = ["Ayesha","Karim","Sadia","Tamim","Nabila"]`: print the highest mark, the lowest mark, and the **name** of the topper.
#5. Make this 2D array `[[1,2,3,4],[5,6,7,8],[9,10,11,12]]`. Print the 2nd row, the 3rd column, and the block `rows 0–1, columns 1–2`.
#6. Create a 4×4 identity matrix.
#7. Simulate 5 dice rolls — 5 random integers from 1 to 6.



In [23]:
#1)
prices = np.array([500,1200,250,3200,780,60])
print(prices*1.15)


[ 575.  1380.   287.5 3680.   897.    69. ]


In [24]:
#2)
print(np.zeros((3,3)))
print(np.full((3,3),9))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [25]:
#3)
print(np.arange(0,51,5))
print(np.linspace(0,100,5))

[ 0  5 10 15 20 25 30 35 40 45 50]
[  0.  25.  50.  75. 100.]


In [27]:
#4)
names = np.array(["Aysha","karim","sadia","tamim","nabila"])
marks = np.array([72,88,65,91,80])
print(marks.max())
print(marks.min())
print(names[marks.argmax()])

91
65
tamim


In [29]:
#5)
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[1])
print(a[:,2])
print(a[0:2,1:3])

[5 6 7 8]
[ 3  7 11]
[[2 3]
 [6 7]]


In [30]:
#6)
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
#7)
print(np.random.randint(1,7,5))

[5 1 4 4 6]
