# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
# A vector is a 1D array  and a matrix is a 2D array.This is the major difference between a "Vector" and "Matrix"

**2. How to import `NumPy` library?** 

In [329]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [330]:
list_1 = [1,2,3,4,5]

In [331]:
array_1 = np.array([1,2,3,4,5])
print(type(array_1))
print(array_1.dtype)

<class 'numpy.ndarray'>
int64


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [332]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [333]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [334]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [335]:
np.ones(5)

array([1., 1., 1., 1., 1.])

**8. Generate an array of "5" tens.**

In [336]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [337]:
np.arange(52,100,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [338]:
np.linspace(0,1,10,retstep=True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 np.float64(0.1111111111111111))

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [339]:
arr=np.arange(1,26)


In [340]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [341]:
np.shape=(5,5)

**12. Please generate the following matrix.**

In [342]:

#i haven't show any matrix in question.

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [343]:
print(np.linspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**14. What is the main difference between `linspace()` and `arange()`?**

In [344]:
#arange use step size between number as third argument and linspace use total number of samples ass 3rd argument.this is the main differenc of linspace and arange


**15. How to generate a single random integer number using NumPy built-in function?**

In [345]:
np.random.randint(1,100)

54

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [346]:
np.random.rand(7,5)

array([[0.37300479, 0.46632867, 0.31875856, 0.13634838, 0.73328827],
       [0.65391302, 0.76156924, 0.00302778, 0.87091449, 0.12821525],
       [0.4049769 , 0.20025772, 0.6615281 , 0.69870418, 0.49706338],
       [0.08434802, 0.42360838, 0.04870492, 0.34626781, 0.39719442],
       [0.47505109, 0.79473256, 0.36247663, 0.98012258, 0.22499348],
       [0.22279443, 0.22686209, 0.1483023 , 0.66575721, 0.9355677 ],
       [0.07886612, 0.6101615 , 0.15297453, 0.93944202, 0.23608973]])

**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [347]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 